- src/itest/java/uk/gov/companieshouse/charges/data/repository/RepositoryITest.java
- src/itest/resources/company-api-request-data.json
- src/main/java/uk/gov/companieshouse/charges/data/config/ApplicationConfig.java
- src/main/java/uk/gov/companieshouse/charges/data/config/MongoConfig.java
- src/main/java/uk/gov/companieshouse/charges/data/controller/ChargesController.java
- src/main/java/uk/gov/companieshouse/charges/data/converter/ChargeApiReadConverter.java
- src/main/java/uk/gov/companieshouse/charges/data/converter/ChargeApiWriteConverter.java
- src/main/java/uk/gov/companieshouse/charges/data/model/ChargesDocument.java
- src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
- src/main/resources/application.yml
DSND-541:Implement MongoDb transactions
> DSND-541:Implement MongoDb transactions

- src/main/java/uk/gov/companieshouse/charges/data/api/ApiClientServiceImpl.java
- src/main/java/uk/gov/companieshouse/charges/data/api/ChargesApiService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/companieshouse/charges/data/api/ChargesApiClientServiceTest.java
This should address the issue with the API Key when calling CHS-Kakfa-API. We still need to identify the correct API Key to use.
> dsnd-542 - Addressed issues with API Key

- src/main/java/uk/gov/companieshouse/charges/data/api/ChargesApiService.java
- src/main/java/uk/gov/companieshouse/charges/data/config/ExceptionHandlerConfig.java
DSND-541: Added Logger in generic exception handler
> DSND-541: Added Logger in generic exception handler

- pom.xml
DSND-541: Update private java sdk version to 2.0.130
> DSND-541: Update private java sdk version to 2.0.130

- pom.xml
DSND-541: Update private jdk version
> DSND-541: Update private jdk version

- src/main/java/uk/gov/companieshouse/charges/data/config/ExceptionHandlerConfig.java
- src/main/java/uk/gov/companieshouse/charges/data/model/ChargesDocument.java
- src/main/java/uk/gov/companieshouse/charges/data/repository/ChargesRepository.java
- src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
- src/main/java/uk/gov/companieshouse/charges/data/tranform/ChargesTransformer.java
fix updateCharges duplicate key exception.
> fix updateCharges duplicate key exception

- pom.xml
- src/main/java/uk/gov/companieshouse/charges/data/api/ApiClientServiceImpl.java
- src/main/java/uk/gov/companieshouse/charges/data/api/ChargesApiService.java
- src/main/java/uk/gov/companieshouse/charges/data/api/ChsKafkaApiClientServiceImpl.java
- src/main/java/uk/gov/companieshouse/charges/data/api/CompanyMetricsApiClientImpl.java
- src/main/java/uk/gov/companieshouse/charges/data/api/CompanyMetricsApiService.java
- src/main/java/uk/gov/companieshouse/charges/data/controller/ChargesController.java
- src/main/java/uk/gov/companieshouse/charges/data/repository/ChargesRepository.java
- src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/companieshouse/charges/data/api/ChargesApiClientServiceTest.java
- src/test/java/uk/gov/companieshouse/charges/data/api/CompanyMetricsApiServiceTest.java
- src/test/java/uk/gov/companieshouse/charges/data/controller/ChargesControllerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/service/ChargesServiceTest.java
- src/test/resources/company-metrics-data.json
DSND-687:Expose a GET public endpoint for Individual Company Id
> DSND-687:Expose a GET public endpoint for Individual Company Id

- src/main/java/uk/gov/companieshouse/charges/data/controller/ChargesController.java
- src/main/java/uk/gov/companieshouse/charges/data/converter/ChargeApiReadConverter.java
- src/main/java/uk/gov/companieshouse/charges/data/serialization/LocalDateDeSerializer.java
- src/main/java/uk/gov/companieshouse/charges/data/serialization/LocalDateSerializer.java
- src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
- src/main/java/uk/gov/companieshouse/charges/data/tranform/ChargesTransformer.java
- src/main/java/uk/gov/companieshouse/charges/data/util/DateFormatter.java
- src/test/java/uk/gov/companieshouse/charges/data/api/CompanyMetricsApiServiceTest.java
- src/test/java/uk/gov/companieshouse/charges/data/controller/ChargesControllerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/util/DateFormatterTest.java
DSND-687: Fix date serlisation/deserialisation issue. Expose unpaged variation of getCharges endpoint.
>  DSND-687: Fix date serlisation/deserialisation issue. Expose unpaged variation of getCharges endpoint.

- src/main/java/uk/gov/companieshouse/charges/data/serialization/LocalDateDeSerializer.java
- src/main/java/uk/gov/companieshouse/charges/data/serialization/LocalDateSerializer.java
- src/test/java/uk/gov/companieshouse/charges/data/converter/ChargesConverterTest.java
- src/test/java/uk/gov/companieshouse/charges/data/util/DateFormatterTest.java
- src/test/resources/charges-test-DB-record.json
SND-687: Fix date deserialisation issue where date was stored as NumberLong.
> SND-687: Fix date deserialisation issue where date was stored as NumberLong.

- src/main/java/uk/gov/companieshouse/charges/data/serialization/LocalDateDeSerializer.java
- src/test/resources/charges-test-DB-record.json
DSND-687: Fix date deserialisation issue where NumberLong date -578275200000 was outside the LocalDate epoch range.
> DSND-687: Fix date deserialisation issue where NumberLong date -578275200000 was outside the LocalDate epoch range.

- src/main/java/uk/gov/companieshouse/charges/data/api/CompanyMetricsApiService.java
> DSND-687: Improve logging

- src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
- src/test/java/uk/gov/companieshouse/charges/data/service/ChargesServiceTest.java
Should have been when no 2xx series response not just any response other than 200
> bug-DSND-817-510 when chs-kafka-api returning non 200 response.

- src/itest/java/uk/gov/companieshouse/charges/data/CucumberFeaturesRunnerITest.java
- src/itest/java/uk/gov/companieshouse/charges/data/config/WiremockTestConfig.java
- src/itest/java/uk/gov/companieshouse/charges/data/steps/ChargesApiSteps.java
- src/itest/resources/features/charges-api.feature
- src/itest/resources/payload/input/Insolvency_cases_Invalid_input.json
- src/itest/resources/payload/input/Invalid_payload.json
- src/itest/resources/payload/output/Additional_notices_Happy_Path_output.json
- src/itest/resources/payload/output/Insolvency_Company_Metrics_output.json
- src/main/java/uk/gov/companieshouse/charges/data/config/ExceptionHandlerConfig.java
DSND-700:Charges Data API Error/Retry Integration Test Scenarios
> DSND-700:Charges Data API Error/Retry Integration Test Scenarios

- src/main/java/uk/gov/companieshouse/charges/data/controller/ChargesController.java
- src/main/java/uk/gov/companieshouse/charges/data/exceptions/ServiceUnavailableException.java
- src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
- src/test/java/uk/gov/companieshouse/charges/data/controller/ChargesControllerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/service/ChargesServiceTest.java
DSND:782: Added a charge delete end point to delete the charges from company mortgages.
> DSND-782: Added a delete functionality

- pom.xml
- src/itest/resources/payload/input/Additional_notices_Happy_Path_input.json
- src/itest/resources/payload/input/Insolvency_cases_Happy_Path_input.json
- src/itest/resources/payload/input/Insolvency_cases_Invalid_input.json
- src/itest/resources/payload/input/Scott_alterations_input.json
- src/itest/resources/payload/input/alterations_to_order_input.json
- src/itest/resources/payload/input/assets_ceased_released_Input.json
- src/itest/resources/payload/input/charge-api-request-data-1.json
- src/itest/resources/payload/input/charge-api-request-data-2.json
- src/itest/resources/payload/input/created_on_input.json
- src/itest/resources/payload/input/floating_charge_input.json
- src/itest/resources/payload/input/more_than_4_persons_input.json
- src/itest/resources/payload/input/obligation_secured_&_nature_of_charge_Happy_Path_input.json
- src/itest/resources/payload/input/satisfied_on_Happy_Path_input.json
- src/itest/resources/payload/output/Additional_notices_Happy_Path_output.json
- src/itest/resources/payload/output/Insolvency_cases_Happy_Path_output.json
- src/itest/resources/payload/output/Scott_alterations_output.json
- src/itest/resources/payload/output/alterations_to_order_output.json
- src/itest/resources/payload/output/assets_ceased_released_output.json
- src/itest/resources/payload/output/created_on_output.json
- src/itest/resources/payload/output/floating_charge_output.json
- src/itest/resources/payload/output/more_than_4_persons_output.json
- src/itest/resources/payload/output/obligation_secured_&_nature_of_charge_Happy_Path_output.json
- src/itest/resources/payload/output/satisfied_on_Happy_Path_output.json
Updating private api SDK version in POM file and also json files for integration testing
> Updating private api SDK version in POM file and also json files for integration testing

- src/main/resources/application.yml
Change to yml file should have been included in original merge but somehow got missed.
> Updated application.yml to ignore null json values.

- src/itest/java/uk/gov/companieshouse/charges/data/repository/RepositoryITest.java
- src/main/java/uk/gov/companieshouse/charges/data/config/ChargesApplicationConfig.java
- src/main/java/uk/gov/companieshouse/charges/data/converter/OffsetDateTimeReadConverter.java
- src/main/java/uk/gov/companieshouse/charges/data/converter/OffsetDateTimeWriteConverter.java
- src/main/java/uk/gov/companieshouse/charges/data/model/ChargesDocument.java
- src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
- src/main/java/uk/gov/companieshouse/charges/data/transform/ChargesTransformer.java
- src/test/java/uk/gov/companieshouse/charges/data/controller/ChargesControllerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/service/ChargesServiceTest.java
- src/test/java/uk/gov/companieshouse/charges/data/transform/ChargesTransformerTest.java
DSND-1015 - Change to store the delta_at as received by CHS Delta API
> DSND-1015 - Change to store the delta_at as received by CHS Delta API

- src/main/java/uk/gov/companieshouse/charges/data/controller/ChargesController.java
- src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
- src/test/java/uk/gov/companieshouse/charges/data/controller/ChargesControllerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/service/ChargesServiceTest.java
updated the charges service class to extract the company number and call the invoke chs kafka api with it to construct the uri.
> hotfix: updating the resource uri with company number

- src/main/java/uk/gov/companieshouse/charges/data/config/ExceptionHandlerConfig.java
DSND-1085 - Handling HttpRequestMethodNotSupportedException returning 405 Method Not Allowed
> DSND-1085 - Handling HttpRequestMethodNotSupportedException

- pom.xml
- src/itest/resources/payload/input/12345678910123456789.json
- src/itest/resources/payload/input/123456789101236666.json
- src/itest/resources/payload/input/Insolvency_cases_Happy_Path_input.json
- src/itest/resources/payload/input/Insolvency_cases_Invalid_input.json
- src/itest/resources/payload/input/charge-api-request-data-1.json
- src/itest/resources/payload/input/charge-api-request-data-2.json
- src/itest/resources/payload/input/chs-kafka-api-12345678910123456789.json
- src/itest/resources/payload/output/Insolvency_cases_Happy_Path_output.json
- src/main/resources/specifications/private.api.ch.gov.uk-specifications/charges/charges.json
- src/test/resources/charges-api-request-data.json
DSND-1110 Update private-api-sdk-java.version in POM file and updated json files for testing
> DSND-1110 Update private-api-sdk-java.version in POM file

- src/itest/java/uk/gov/companieshouse/charges/data/steps/ChargesApiSteps.java
- src/itest/resources/features/charges-api-happy-path.feature
> DSND-1037: added equired integration tests around chs kafka api

- src/main/java/uk/gov/companieshouse/charges/data/config/ExceptionHandlerConfig.java
- src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
Exception Response refactoring + addressing possible NPE issue
> Exception Response refactoring + addressing possible NPE issue

- src/main/java/uk/gov/companieshouse/charges/data/config/ExceptionHandlerConfig.java
Changes to include the x-request-id if available
> Changes to include the x-request-id if available

- src/main/java/uk/gov/companieshouse/charges/data/api/CompanyMetricsApiService.java
DSND-1160 Log improvements for 410 GONE for GetCompanyMetric response
> DSND-1160 Log improvements for 410 GONE for GetCompanyMetric response

- src/main/java/uk/gov/companieshouse/charges/data/config/LoggingConfig.java
- src/main/java/uk/gov/companieshouse/charges/data/serialization/LocalDateDeSerializer.java
- src/test/java/uk/gov/companieshouse/charges/data/serialization/LocalDateDeSerializerTest.java
DSND-1165 LocalDateDeSerializer improvements
> DSND-1165 LocalDateDeSerializer improvements

- src/itest/java/uk/gov/companieshouse/charges/data/config/WiremockTestConfig.java
- src/itest/resources/features/charges-api-delete.feature
- src/itest/resources/features/charges-api-happy-path.feature
- src/main/java/uk/gov/companieshouse/charges/data/api/CompanyMetricsApiService.java
- src/main/java/uk/gov/companieshouse/charges/data/controller/ChargesController.java
- src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
- src/test/java/uk/gov/companieshouse/charges/data/service/ChargesServiceTest.java
Replaced HTTP GONE with HTTP NOT_FOUND
BI-11640
> Replaced HTTP GONE with HTTP NOT_FOUND

- src/itest/java/uk/gov/companieshouse/charges/data/config/WiremockTestConfig.java
- src/itest/resources/features/charges-api-delete.feature
- src/itest/resources/features/charges-api-happy-path.feature
- src/main/java/uk/gov/companieshouse/charges/data/api/CompanyMetricsApiService.java
- src/main/java/uk/gov/companieshouse/charges/data/controller/ChargesController.java
- src/test/java/uk/gov/companieshouse/charges/data/service/ChargesServiceTest.java
Amendments to revert changes made to replace GONE with NOT FOUND
BI-11640
> Amendments to revert changes made to replace GONE with NOT FOUND

- src/main/java/uk/gov/companieshouse/charges/data/api/ApiClientService.java
- src/main/java/uk/gov/companieshouse/charges/data/api/ApiClientServiceImpl.java
- src/main/java/uk/gov/companieshouse/charges/data/api/CompanyMetricsApiService.java
* Add getInternalApiUrl method to ApiClientService
* Add extra log message in CompanyMetricsApiService
> DSND-1279 Add log message to determine internal url

- src/main/java/uk/gov/companieshouse/charges/data/api/CompanyMetricsApiService.java
- Add Http response code and status message to error messages logging.
> DSND-1279 Add Http response to error messages

- src/itest/java/uk/gov/companieshouse/charges/data/repository/ChargesRepositoryITest.java
- src/main/java/uk/gov/companieshouse/charges/data/controller/ChargesController.java
- src/main/java/uk/gov/companieshouse/charges/data/model/RequestCriteria.java
- src/main/java/uk/gov/companieshouse/charges/data/repository/ChargesRepository.java
- src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
- src/test/java/uk/gov/companieshouse/charges/data/controller/ChargesControllerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/service/ChargesServiceTest.java
* Add integration test for charges repository
* Refactor controller to pass RequestCriteria to service
* Modify findCharges service method to pass Sort criteria to repository
* Fix failing unit tests and refactor
[DSND-1304](https://companieshouse.atlassian.net/browse/DSND-1304)
> DSND 1304 Add sort functionality

- src/itest/java/uk/gov/companieshouse/charges/data/repository/ChargesRepositoryITest.java
- src/main/java/uk/gov/companieshouse/charges/data/repository/ChargesRepository.java
- src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
- src/test/java/uk/gov/companieshouse/charges/data/service/ChargesServiceTest.java
* Sorts charges by created_on field or delivered_on field if created_on is absent.
* Secondary sorts on charge_number
* Filter still works as expected, tested locally.
[DSND-1306](https://companieshouse.atlassian.net/browse/DSND-1306)
> DSND-1306 Charges aggregation sort

- src/itest/java/uk/gov/companieshouse/charges/data/repository/ChargesRepositoryITest.java
- src/main/java/uk/gov/companieshouse/charges/data/model/ChargesAggregate.java
- src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
- src/test/java/uk/gov/companieshouse/charges/data/service/ChargesServiceTest.java
* If no charges are matched in the repository then total_count will be an empty list which needs checked for emptiness before indexing.
[DSND-1441](https://companieshouse.atlassian.net/browse/DSND-1441)
[DSND-1441]: https://companieshouse.atlassian.net/browse/DSND-1441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-1411 Fix index out of bounds exception

- src/itest/java/uk/gov/companieshouse/charges/data/steps/ChargesApiSteps.java
- src/main/java/uk/gov/companieshouse/charges/data/auth/EricTokenAuthenticationFilter.java
- src/test/java/uk/gov/companieshouse/charges/data/auth/EricTokenAuthenticationFilterTest.java
- src/test/java/uk/gov/companieshouse/charges/data/controller/ChargesControllerTest.java
Implemented eric authentication filter fix.
[DSND-1543](https://companieshouse.atlassian.net/browse/DSND-1543)
[DSND-1543]: https://companieshouse.atlassian.net/browse/DSND-1543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-1543 Implement check internal user privileges fix

- pom.xml
- src/main/java/uk/gov/companieshouse/charges/data/auth/EricTokenAuthenticationFilter.java
- src/main/java/uk/gov/companieshouse/charges/data/config/ExceptionHandlerConfig.java
- src/main/java/uk/gov/companieshouse/charges/data/config/WebSecurityConfig.java
- src/main/java/uk/gov/companieshouse/charges/data/controller/ChargesController.java
- src/main/java/uk/gov/companieshouse/charges/data/controller/HealthCheckController.java
- src/main/java/uk/gov/companieshouse/charges/data/converter/EnumConverters.java
- src/suppress.xml
- src/test/java/uk/gov/companieshouse/charges/data/api/CompanyMetricsApiServiceTest.java
- src/test/java/uk/gov/companieshouse/charges/data/auth/EricTokenAuthenticationFilterTest.java
- src/test/java/uk/gov/companieshouse/charges/data/config/ExceptionHandlerConfigTest.java
- src/test/java/uk/gov/companieshouse/charges/data/controller/ChargesControllerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/controller/HealthCheckControllerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/service/ChargesServiceTest.java
https://companieshouse.atlassian.net/browse/JU-116
Make code changes and library changes to Java v:21
Clearing critical vulnerabilities (if other vulnerabilities can be resolved, then do so)
Code cleanup (clear configs specific to Mesos & update docker images)
> JU-116 - Java 21 Migration

- pom.xml
- src/main/java/uk/gov/companieshouse/charges/data/config/WebSecurityConfig.java
- src/test/java/uk/gov/companieshouse/charges/data/controller/ChargesControllerTest.java
Jira Ticket : https://companieshouse.atlassian.net/browse/SEC-50
> Adding CORS filter to the api

- src/main/java/uk/gov/companieshouse/charges/data/api/CompanyMetricsApiService.java
[DSND-1295](https://companieshouse.atlassian.net/browse/DSND-1295)
[DSND-1295]: https://companieshouse.atlassian.net/browse/DSND-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-1295: Move log message which was never hit

- pom.xml
- src/itest/java/uk/gov/companieshouse/charges/data/steps/ChargesApiSteps.java
- src/itest/resources/features/charges-api-delete.feature
- src/itest/resources/features/charges-api-error-retry.feature
- src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
- src/test/java/uk/gov/companieshouse/charges/data/service/ChargesServiceTest.java
* processing order changed for upserts and deletes
* compensatory transaction removed from upsert flow
[DSND-3023](https://companieshouse.atlassian.net/browse/DSND-3023)
[DSND-3023]: https://companieshouse.atlassian.net/browse/DSND-3023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-3023: Change processing order for upsert and delete

- src/itest/java/uk/gov/companieshouse/charges/data/config/WiremockTestConfig.java
- src/itest/java/uk/gov/companieshouse/charges/data/repository/ChargesRepositoryITest.java
- src/itest/java/uk/gov/companieshouse/charges/data/steps/ChargesApiSteps.java
- src/main/java/uk/gov/companieshouse/charges/data/api/ApiClientServiceImpl.java
- src/main/java/uk/gov/companieshouse/charges/data/controller/ChargesController.java
- src/main/java/uk/gov/companieshouse/charges/data/converter/OffsetDateTimeReadConverter.java
- src/test/java/uk/gov/companieshouse/charges/data/api/ChargesApiClientServiceTest.java
- src/test/java/uk/gov/companieshouse/charges/data/api/CompanyMetricsApiServiceTest.java
- src/test/java/uk/gov/companieshouse/charges/data/auth/EricTokenAuthenticationFilterTest.java
- src/test/java/uk/gov/companieshouse/charges/data/config/ExceptionHandlerConfigTest.java
- src/test/java/uk/gov/companieshouse/charges/data/controller/ChargesControllerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/converter/ChargeApiReadConverterTest.java
- src/test/java/uk/gov/companieshouse/charges/data/converter/ChargeApiWriteConverterTest.java
- src/test/java/uk/gov/companieshouse/charges/data/converter/ChargesConverterTest.java
- src/test/java/uk/gov/companieshouse/charges/data/converter/EnumConvertersTest.java
- src/test/java/uk/gov/companieshouse/charges/data/serialization/LocalDateSerializerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/serialization/LocalDateTimeDeSerializerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/serialization/LocalDateTimeSerializerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/serialization/NonBlankStringSerializerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/serialization/NotNullFieldObjectSerializerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/serialization/OffsetDateTimeDeSerializerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/serialization/OffsetDateTimeSerializerTest.java
- src/test/java/uk/gov/companieshouse/charges/data/service/ChargesServiceTest.java
- src/test/java/uk/gov/companieshouse/charges/data/transform/ChargesTransformerTest.java
[DSND-2871](https://companieshouse.atlassian.net/browse/DSND-2871)
[DSND-2871]: https://companieshouse.atlassian.net/browse/DSND-2871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2871: Fix simple Sonarlint issues

- pom.xml
- src/itest/java/uk/gov/companieshouse/charges/data/steps/ChargesApiSteps.java
- src/itest/resources/features/charges-api-error.feature
- src/itest/resources/payload/input/Insolvency_cases_stale_input.json
- src/main/java/uk/gov/companieshouse/charges/data/service/ChargesService.java
- src/test/java/uk/gov/companieshouse/charges/data/service/ChargesServiceTest.java
* Update parent pom, private api sdk java version
* Update spring and jib maven plugin version
* Add test case to cover 409 response
Resolves [DSND-3193](https://companieshouse.atlassian.net/browse/DSND-3193)
[DSND-3193]: https://companieshouse.atlassian.net/browse/DSND-3193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-3193: Throw ConflictException on stale upsert

- pom.xml
https://companieshouse.atlassian.net/browse/ASM-506
Add latest Sonar config to Pom
> ASM-506 Add latest Sonar config to Pom
